package com.app.bzpower.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.username
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.realname
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.telephone
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.type
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.voltage
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    private String voltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.company_id
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    private Company companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.realname
     *
     * @return the value of admin.realname
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.realname
     *
     * @param realname the value for admin.realname
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.telephone
     *
     * @return the value of admin.telephone
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.telephone
     *
     * @param telephone the value for admin.telephone
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.type
     *
     * @return the value of admin.type
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.type
     *
     * @param type the value for admin.type
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.voltage
     *
     * @return the value of admin.voltage
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public String getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.voltage
     *
     * @param voltage the value for admin.voltage
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public void setVoltage(String voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.company_id
     *
     * @return the value of admin.company_id
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public Company getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.company_id
     *
     * @param companyId the value for admin.company_id
     *
     * @mbg.generated Thu Aug 22 17:02:20 CST 2019
     */
    public void setCompanyId(Company companyId) {
        this.companyId = companyId;
    }
}