package com.app.bzpower.entity;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbg.generated Thu Aug 22 17:02:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.companyName
     *
     * @mbg.generated Thu Aug 22 17:02:51 CST 2019
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.voltage
     *
     * @mbg.generated Thu Aug 22 17:02:51 CST 2019
     */
    private String voltage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbg.generated Thu Aug 22 17:02:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbg.generated Thu Aug 22 17:02:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.companyName
     *
     * @return the value of company.companyName
     *
     * @mbg.generated Thu Aug 22 17:02:51 CST 2019
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.companyName
     *
     * @param companyname the value for company.companyName
     *
     * @mbg.generated Thu Aug 22 17:02:51 CST 2019
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.voltage
     *
     * @return the value of company.voltage
     *
     * @mbg.generated Thu Aug 22 17:02:51 CST 2019
     */
    public String getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.voltage
     *
     * @param voltage the value for company.voltage
     *
     * @mbg.generated Thu Aug 22 17:02:51 CST 2019
     */
    public void setVoltage(String voltage) {
        this.voltage = voltage;
    }
}