package com.app.bzpower.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.realname
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.voltage
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    private String voltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company_id
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    private Company companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.transformersub_id
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    private TransformerSub transformersubId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.remarks
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.realname
     *
     * @return the value of user.realname
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.realname
     *
     * @param realname the value for user.realname
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.voltage
     *
     * @return the value of user.voltage
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public String getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.voltage
     *
     * @param voltage the value for user.voltage
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public void setVoltage(String voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.company_id
     *
     * @return the value of user.company_id
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public Company getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.company_id
     *
     * @param companyId the value for user.company_id
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public void setCompanyId(Company companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.transformersub_id
     *
     * @return the value of user.transformersub_id
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.remarks
     *
     * @return the value of user.remarks
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    public TransformerSub getTransformersubId() {
		return transformersubId;
	}

	public void setTransformersubId(TransformerSub transformersubId) {
		this.transformersubId = transformersubId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.remarks
     *
     * @param remarks the value for user.remarks
     *
     * @mbg.generated Thu Aug 22 17:04:13 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}