package com.app.bzpower.dao;

import com.app.bzpower.entity.Lockinfo;
import com.app.bzpower.entity.PageData;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LockinfoMapper {
	
	List<Lockinfo> selectLockList(@Param("pageData") PageData pageData, 
			@Param("voltage") String voltage ,
			@Param("companyId") int companyId);
	
	
	Lockinfo selectLockByDid(String did);
	
	long countByExample(Lockinfo example);
	
	
	Lockinfo selectByPrimaryKey(Integer id);
	
	
	int insertSelective(Lockinfo record);
	
	
	int deleteByPrimaryKey(Integer id);
	
	int updateByPrimaryKeySelective(Lockinfo record);
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table lockinfo
//     *
//     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
//     */
//    long countByExample(Lockinfo example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table lockinfo
//     *
//     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
//     */
//    int deleteByExample(Lockinfo example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table lockinfo
//     *
//     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
//     */
//    
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table lockinfo
//     *
//     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
//     */
//    int insert(Lockinfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table lockinfo
//     *
//     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
//     */
//    
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table lockinfo
//     *
//     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
//     */
//    List<Lockinfo> selectByExample(Lockinfo example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table lockinfo
//     *
//     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
//     */
//    
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table lockinfo
//     *
//     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
//     */
//    int updateByExampleSelective(@Param("record") Lockinfo record, @Param("example") Lockinfo example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table lockinfo
//     *
//     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
//     */
//    int updateByExample(@Param("record") Lockinfo record, @Param("example") Lockinfo example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table lockinfo
//     *
//     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
//     */
//    
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table lockinfo
//     *
//     * @mbg.generated Thu Aug 22 17:09:12 CST 2019
//     */
//    int updateByPrimaryKey(Lockinfo record);
}