package com.app.bzpower.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.app.bzpower.entity.PageData;
import com.app.bzpower.entity.TransformerSub;

public interface TransformersubMapper {
	
	List<TransformerSub> selectTransformerSubList(
			@Param("pageData")PageData pageData,
			@Param("voltage")String voltage, 
			@Param("companyname")String companyname);
	
	List<TransformerSub> selectTransformerSubListByCompanyId(@Param("companyId") int companyId);

	List<TransformerSub> selectTransfromerSub(@Param("companyId")int companyId, @Param("voltage")String voltage) ;
	
	int insertSelective(TransformerSub record);
	
	int deleteByPrimaryKey(Integer id);
	
	
	int updateByPrimaryKeySelective(TransformerSub record);
	
	
	TransformerSub selectByPrimaryKey(Integer id);
	
	long countByExample(TransformerSub example);
	
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table transformersub
//	 * @mbg.generated  Thu Aug 22 17:18:06 CST 2019
//	 */
//	long countByExample(TransformerSub example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table transformersub
//	 * @mbg.generated  Thu Aug 22 17:18:06 CST 2019
//	 */
//	int deleteByExample(TransformerSub example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table transformersub
//	 * @mbg.generated  Thu Aug 22 17:18:06 CST 2019
//	 */
//	
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table transformersub
//	 * @mbg.generated  Thu Aug 22 17:18:06 CST 2019
//	 */
//	int insert(TransformerSub record);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table transformersub
//	 * @mbg.generated  Thu Aug 22 17:18:06 CST 2019
//	 */
//	int insertSelective(TransformerSub record);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table transformersub
//	 * @mbg.generated  Thu Aug 22 17:18:06 CST 2019
//	 */
//	List<TransformerSub> selectByExample(TransformerSub example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table transformersub
//	 * @mbg.generated  Thu Aug 22 17:18:06 CST 2019
//	 */
//	TransformerSub selectByPrimaryKey(Integer id);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table transformersub
//	 * @mbg.generated  Thu Aug 22 17:18:06 CST 2019
//	 */
//	int updateByExampleSelective(@Param("record") TransformerSub record,
//			@Param("example") TransformerSub example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table transformersub
//	 * @mbg.generated  Thu Aug 22 17:18:06 CST 2019
//	 */
//	int updateByExample(@Param("record") TransformerSub record, @Param("example") TransformerSub example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table transformersub
//	 * @mbg.generated  Thu Aug 22 17:18:06 CST 2019
//	 */
//	
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table transformersub
//	 * @mbg.generated  Thu Aug 22 17:18:06 CST 2019
//	 */
//	int updateByPrimaryKey(TransformerSub record);
}