package com.app.bzpower.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.app.bzpower.entity.Admin;
import com.app.bzpower.entity.PageData;
import com.app.bzpower.entity.Requestlog;
import com.app.bzpower.entity.User;

public interface UserMapper {

	List<User> selectUserList(@Param("pageData") PageData pageData, @Param("admin") Admin admin);

	User selectByPrimaryKey(Integer id);

	long countByExample(User example);

	int updateByPrimaryKeySelective(User record);

	int deleteByPrimaryKey(Integer id);

	int insertSelective(User record);

	User selectUserByPhone(String phone);

	List<User> selectUserListByCompanyId(@Param("voltage") String voltage, @Param("companyId") int companyId);

//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
//	 * @mbg.generated  Thu Aug 22 17:04:13 CST 2019
//	 */
//	long countByExample(User example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
//	 * @mbg.generated  Thu Aug 22 17:04:13 CST 2019
//	 */
//	int deleteByExample(User example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
//	 * @mbg.generated  Thu Aug 22 17:04:13 CST 2019
//	 */
//	int deleteByPrimaryKey(Integer id);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
//	 * @mbg.generated  Thu Aug 22 17:04:13 CST 2019
//	 */
//	int insert(User record);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
//	 * @mbg.generated  Thu Aug 22 17:04:13 CST 2019
//	 */
//	int insertSelective(User record);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
//	 * @mbg.generated  Thu Aug 22 17:04:13 CST 2019
//	 */
//	List<User> selectByExample(User example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
//	 * @mbg.generated  Thu Aug 22 17:04:13 CST 2019
//	 */
//	
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
//	 * @mbg.generated  Thu Aug 22 17:04:13 CST 2019
//	 */
//	int updateByExampleSelective(@Param("record") User record, @Param("example") User example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
//	 * @mbg.generated  Thu Aug 22 17:04:13 CST 2019
//	 */
//	int updateByExample(@Param("record") User record, @Param("example") User example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
//	 * @mbg.generated  Thu Aug 22 17:04:13 CST 2019
//	 */
//	
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
//	 * @mbg.generated  Thu Aug 22 17:04:13 CST 2019
//	 */
//	int updateByPrimaryKey(User record);
}